site_name: icar_test
pages:
- Home: index.md
- Compiling: compiling.md
- Running: running.md
- Developing: developing.md
- Errors: errors.md
theme: readthedocs
google_analytics: ['UA-108421993-4', 'icar_test.readthedocs.org']
